version: "3"
services:
  pgbouncer:
    image: brainsam/pgbouncer:1.7.2
    environment:
      - LISTEN_PORT=5432
      - DB_HOST=postgres
      - DB_USER=test
      - DB_PASSWORD=test
      - POOL_MODE=transaction
    ports:
      - "5432:5432"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "6432:5432"
  
  dotnet:
    image: microsoft/dotnet:2-sdk-jessie
    environment:
      - DB_HOST=${TARGET:-pgbouncer}
    depends_on:
      - pgbouncer
      - postgres
    volumes:
      - ./:/work
    working_dir: /work
    command: dotnet run
